services:
  db:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: game_reviews_db
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db
      - backup:/backup
      - mongo_init:/docker-entrypoint-initdb.d

  django-app:
    build:
      context: .
    image: rotten_scores:1.0
    container_name: django-app
    volumes:
      - app_data:/app
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=src.backend.rotten_scores.settings
      - MONGO_DB_NAME=game_reviews_db
      - MONGO_DB_USER=root
      - MONGO_DB_PASSWORD=root
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
    networks:
      - app-network

volumes:
  mongo_data:
  backup:
  mongo_init:
  app_data:

networks:
  app-network:
    driver: bridge
